" 显示行号
set number

" 自动缩进
" set autoindent
" set cindent

" Tab键的宽度
set tabstop=2

" 统一缩进为2
set softtabstop=2
set shiftwidth=2
" 编辑时将Tab转换为空格
set expandtab

" 编码设置
set enc=utf-8
set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936

" 语言设置
set langmenu=zh_CN.UTF-8
set helplang=cn

" 解决乱码
let &termencoding=&encoding
set fileencodings=utf-8,gbk,ucs-bom,cp936

" 我的状态行显示的内容（包括文件类型和解码）
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]
set statusline=[%F]%y%r%m%*%=[Line:%l/%L,Column:%c][%p%%]

" 总是显示状态行
set laststatus=2

" 在编辑过程中，在右下角显示光标位置的状态行
set ruler

" 命令行（在状态行下）的高度，默认为1，这里是2
set cmdheight=1

" 高亮显示普通txt文件（需要txt.vim脚本）
au BufRead,BufNewFile *  setfiletype txt

syntax enable
syntax on
colorscheme desert

set smarttab
